Team.create!(id: 1, name: "Argentina", city: "Buenos Aires", division: "South America", conference: "West")
Team.create!(id: 2, name: "Australia", city: "Sydney", division: "Oceania", conference: "East")
Team.create!(id: 3, name: "Brazil", city: "Rio de Janeiro", division: "South America", conference: "West")
Team.create!(id: 4, name: "Canada", city: "Vancouver", division: "North America", conference: "West")
Team.create!(id: 5, name: "China", city: "Shanghai", division: "Asia", conference: "East")
Team.create!(id: 6, name: "Colombia", city: "Bogota", division: "South America", conference: "West")
Team.create!(id: 7, name: "Cuba", city: "Havana", division: "North America", conference: "West")
Team.create!(id: 8, name: "Dominican Republic", city: "Santo Domingo", division: "North America", conference: "West")
Team.create!(id: 9, name: "Egypt", city: "Cairo", division: "Africa", conference: "East")
Team.create!(id: 10, name: "Ethiopia", city: "Addis Ababa", division: "Africa", conference: "East")
Team.create!(id: 11, name: "Fiji", city: "Suva", division: "Oceania", conference: "East")
Team.create!(id: 12, name: "France", city: "Paris", division: "Europe", conference: "West")
Team.create!(id: 13, name: "Germany", city: "Munich", division: "Europe", conference: "West")
Team.create!(id: 14, name: "India", city: "Calcutta", division: "Asia", conference: "East")
Team.create!(id: 15, name: "Italy", city: "Rome", division: "Europe", conference: "West")
Team.create!(id: 16, name: "Japan", city: "Tokyo", division: "Asia", conference: "East")
Team.create!(id: 17, name: "Kenya", city: "Nairobi", division: "Africa", conference: "East")
Team.create!(id: 18, name: "Mexico", city: "Mexico City", division: "North America", conference: "West")
Team.create!(id: 19, name: "Morocco", city: "Cassblanca", division: "Africa", conference: "East")
Team.create!(id: 20, name: "New Zealand", city: "Wellington", division: "Oceania", conference: "East")
Team.create!(id: 21, name: "Papua New Guinea", city: "Port Moresby", division: "Oceania", conference: "East")
Team.create!(id: 22, name: "Peru", city: "Lima", division: "South America", conference: "West")
Team.create!(id: 23, name: "Russia", city: "Moscow", division: "Asia", conference: "East")
Team.create!(id: 24, name: "Samoa", city: "Apia", division: "Oceania", conference: "East")
Team.create!(id: 25, name: "South Africa", city: "Cape Town", division: "Africa", conference: "East")
Team.create!(id: 26, name: "Spain", city: "Barcelona", division: "Europe", conference: "West")
Team.create!(id: 27, name: "Thailand", city: "Bangkok", division: "Asia", conference: "East")
Team.create!(id: 28, name: "United Kingdom", city: "londom", division: "Europe", conference: "West")
Team.create!(id: 29, name: "United States", city: "New York City", division: "North America", conference: "West")
Team.create!(id: 30, name: "Venezuela", city: "Caracas", division: "South America", conference: "West")

Game.create!(date: Date.parse("29/03/2018"), visitor_id: 19, home_id: 23, complete: true)
Game.create!(date: Date.parse("29/03/2018"), visitor_id: 10, home_id: 16, complete: true)
Game.create!(date: Date.parse("29/03/2018"), visitor_id: 28, home_id: 7, complete: true)
Game.create!(date: Date.parse("29/03/2018"), visitor_id: 3, home_id: 6, complete: false)
Game.create!(date: Date.parse("29/03/2018"), visitor_id: 29, home_id: 4, complete: false)
Game.create!(date: Date.parse("29/03/2018"), visitor_id: 18, home_id: 8, complete: false)
Game.create!(date: Date.parse("29/03/2018"), visitor_id: 30, home_id: 22, complete: false)
Game.create!(date: Date.parse("29/03/2018"), visitor_id: 9, home_id: 2, complete: false)
Game.create!(date: Date.parse("29/03/2018"), visitor_id: 27, home_id: 14, complete: false)
Game.create!(date: Date.parse("29/03/2018"), visitor_id: 12, home_id: 26, complete: false)
Game.create!(date: Date.parse("29/03/2018"), visitor_id: 11, home_id: 20, complete: false)
Game.create!(date: Date.parse("29/03/2018"), visitor_id: 13, home_id: 1, complete: false)
Game.create!(date: Date.parse("29/03/2018"), visitor_id: 21, home_id: 24, complete: false)